apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec: 
  selector: 
    matchLabels:
      app: "ashraf"
      app1: "ahmed"
      app2: "omar"
  replicas: 3
  template:
    metadata:
      name: my-pod
      labels:
        app: "ashraf"
        app1: "ahmed"
        app2: "omar"
    spec:
      containers: 
        - image: ashrafabdo02/project
          name: nginx-container
          imagePullPolicy: IfNotPresent  
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:  
              memory: "100Mi"
              cpu: "100m"
