apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec: 
  selector: 
    matchLabels:
      app: ashraf
  replicas: 3
  template:
    metadata:
      name: my-first-pod
      labels:
        app: ashraf
    spec:
      containers: 
        - image: ashrafabdo02/project
          name: nginx-container
          imagePullPolicy: IfNotPresent  # Corrected typo in imagePullPolicy
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:  # Corrected typo in requests
              memory: "100Mi"
              cpu: "100m"  # Added CPU request example; adjust as needed
